clear all;
close all;

datalength=6000;
samplelingtime=0.008;

%%
wpg=load("wpg.txt");
th_hardware=wpg(:,1:12);
encoder_hardware=wpg(:,13:24);
encoder_hardware(:,4)=-encoder_hardware(:,4);
encoder_hardware(:,9)=-encoder_hardware(:,9);
encoder_hardware(:,10)=-encoder_hardware(:,10);
encoder_hardware(:,11)=-encoder_hardware(:,11);


%%
[r,c]=size(th_hardware);
t=1:r;
t=t*samplelingtime;
%%
figure('name','darwinop3 hardware th desired')
subplot(121);
hold on;
plot(t,th_hardware(:,6),'linewidth',2);plot(t,th_hardware(:,5),'linewidth',2);plot(t,th_hardware(:,4),'linewidth',2);
plot(t,th_hardware(:,3),'linewidth',2);plot(t,th_hardware(:,2),'linewidth',2);plot(t,th_hardware(:,1),'linewidth',2);
legend({'motor5(hip yaw)','motor4(hip roll)','motor3(hip pitch)','motor2(knee pitch)','motor1(ankle pitch)','motor0(ankle roll)'})
ylabel('right joint [rad]');xlabel('[sec]');
hold off;
subplot(122);
hold on;
plot(t,th_hardware(:,7),'linewidth',2);plot(t,th_hardware(:,8),'linewidth',2);plot(t,th_hardware(:,9),'linewidth',2);
plot(t,th_hardware(:,10),'linewidth',2);plot(t,th_hardware(:,11),'linewidth',2);plot(t,th_hardware(:,12),'linewidth',2);
legend({'motor6(hip yaw)','motor7(hip roll)','motor8(hip pitch)','motor9(knee pitch)','motor10(ankle pitch)','motor11(ankle roll)'})
hold off;
set(gcf,'Color','w');
ylabel('left joint [rad]');xlabel('[sec]');

figure('name','theta_compare')
subplot(6,2,1);
hold on;
plot(t,th_hardware(:,6),'linewidth',2);
hold on;
plot(t,encoder_hardware(:,1),'linewidth',2);
hold on;
legend({'desired motor5(hip yaw)','encoder(hip yaw)'});
ylabel('right joint [rad]');xlabel('[sec]');
hold off;
subplot(6,2,2);
hold on;
plot(t,th_hardware(:,7),'linewidth',2);
hold on;
plot(t,encoder_hardware(:,2),'linewidth',2);
hold on;
legend({'desired motor6(hip yaw)','encoder(hip yaw)'});
ylabel('left joint [rad]');xlabel('[sec]');
hold off;
subplot(6,2,3);
hold on;
plot(t,th_hardware(:,5),'linewidth',2);
hold on;
plot(t,encoder_hardware(:,3),'linewidth',2);
hold on;
legend({'desired motor4(hip roll)','encoder(hip roll)'});
ylabel('right joint [rad]');xlabel('[sec]');
hold off;
subplot(6,2,4);
hold on;
plot(t,th_hardware(:,8),'linewidth',2);
hold on;
plot(t,encoder_hardware(:,4),'linewidth',2);
hold on;
legend({'desired motor7(hip roll)','encoder(hip roll)'});
ylabel('left joint [rad]');xlabel('[sec]');
hold off;
subplot(6,2,5);
hold on;
plot(t,th_hardware(:,4),'linewidth',2);
hold on;
plot(t,encoder_hardware(:,5),'linewidth',2);
hold on;
legend({'desired motor3(hip pitch)','encoder(hip pitch)'});
ylabel('right joint [rad]');xlabel('[sec]');
hold off;
subplot(6,2,6);
hold on;
plot(t,th_hardware(:,9),'linewidth',2);
hold on;
plot(t,encoder_hardware(:,6),'linewidth',2);
hold on;
legend({'desired motor8(hip pitch)','encoder(hip pitch)'});
ylabel('right joint [rad]');xlabel('[sec]');
hold off;
subplot(6,2,7);
hold on;
plot(t,th_hardware(:,3),'linewidth',2);
hold on;
plot(t,encoder_hardware(:,7),'linewidth',2);
hold on;
legend({'desired motor2(knee pitch)','encoder(knee pitch)'});
ylabel('right joint [rad]');xlabel('[sec]');
hold off;
subplot(6,2,8);
hold on;
plot(t,th_hardware(:,10),'linewidth',2);
hold on;
plot(t,encoder_hardware(:,8),'linewidth',2);
hold on;
legend({'desired motor9(knee pitch)','encoder(knee pitch)'});
ylabel('left joint [rad]');xlabel('[sec]');
hold off;
subplot(6,2,9);
hold on;
plot(t,th_hardware(:,2),'linewidth',2);
hold on;
plot(t,encoder_hardware(:,9),'linewidth',2);
hold on;
legend({'desired motor1(ankle pitch)','encoder(ankle pitch)'});
ylabel('right joint [rad]');xlabel('[sec]');
hold off;
subplot(6,2,10);
hold on;
plot(t,th_hardware(:,11),'linewidth',2);
hold on;
plot(t,encoder_hardware(:,10),'linewidth',2);
hold on;
legend({'desired motor10(ankle pitch)','encoder(ankle pitch)'});
ylabel('left joint [rad]');xlabel('[sec]');
hold off;
subplot(6,2,11);
hold on;
plot(t,th_hardware(:,1),'linewidth',2);
hold on;
plot(t,encoder_hardware(:,11),'linewidth',2);
hold on;
legend({'desired motor0(ankle roll)','encoder(ankle roll)'});
ylabel('right joint [rad]');xlabel('[sec]');
hold off;
subplot(6,2,12);
hold on;
plot(t,th_hardware(:,12),'linewidth',2);
hold on;
plot(t,encoder_hardware(:,12),'linewidth',2);
hold on;
legend({'desired motor11(ankle roll)','encoder(ankle roll)'});
ylabel('left joint [rad]');xlabel('[sec]');
hold off;
